# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [84]:
# !curl -O 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
import pandas as pd
# users=pd.DataFrame('u.user',sep='|')
users=pd.read_csv('u.user',sep='|')
users.set_index('user_id',inplace=True,drop=True)
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [6]:
import pandas as pd

grouped=users.groupby(['occupation'])
grouped.agg({
    'age':['mean']
})

                     age
                    mean
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [87]:
# grouped=users.groupby(['occupation'])
#defining filter
# mask=users.gender=='M'
# grouped[mask].sort_values(ascending=False)

# # creating filter
# mask=users.gender=='M'
# grouped=users[mask].groupby(['occupation'])
# for name ,subgroup in grouped:
#     print(name)
#     # print(subgroup)
#     print(subgroup.gender.count())
    

grouped=users.groupby(['occupation'])
grouped['gender'].value_counts()
# grouped[mask]

# for name,subgroup in grouped:
#     # print(name)
#     print(subgroup.columns)
#     #defining mask
#     # mask=(subgroup.gender=='M')
#     # subgroup[~mask].value_counts()
#     # # break

occupation     gender
administrator  M          43
               F          36
artist         M          15
               F          13
doctor         M           7
educator       M          69
               F          26
engineer       M          65
               F           2
entertainment  M          16
               F           2
executive      M          29
               F           3
healthcare     F          11
               M           5
homemaker      F           6
               M           1
lawyer         M          10
               F           2
librarian      F          29
               M          22
marketing      M          16
               F          10
none           M           5
               F           4
other          M          69
               F          36
programmer     M          60
               F           6
retired        M          13
               F           1
salesman       M           9
               F           3
scientist      M          28
               F           3
student        M         136
               F          60
technician     M          26
               F           1
writer         M          26
               F          19
Name: count, dtype: int64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [37]:
grouped=users.groupby(['occupation'])
grouped['age'].agg(['min','max'])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [40]:
grouped=users.groupby(['occupation','gender'])
# grouped['age'].mean()
round(grouped.age.aggregate(['mean']))

                      mean
occupation    gender
administrator F       41.0
              M       37.0
artist        F       30.0
              M       32.0
doctor        M       44.0
educator      F       39.0
              M       43.0
engineer      F       30.0
              M       37.0
entertainment F       31.0
              M       29.0
executive     F       44.0
              M       38.0
healthcare    F       40.0
              M       45.0
homemaker     F       34.0
              M       23.0
lawyer        F       40.0
              M       36.0
librarian     F       40.0
              M       40.0
marketing     F       37.0
              M       38.0
none          F       36.0
              M       19.0
other         F       35.0
              M       34.0
programmer    F       32.0
              M       33.0
retired       F       70.0
              M       63.0
salesman      F       27.0
              M       39.0
scientist     F       28.0
              M       36.0
student       F       21.0
              M       23.0
technician    F       38.0
              M       33.0
writer        F       38.0
              M       35.0

### Step 8.  For each occupation present the percentage of women and men

In [98]:
# def womanPercentage(arr):
#     # return pd.to_numeric(arr.values[0]/arr.count())*100

#     return arr.values[0].value_counts().count()
#     # arr.values[0]=0
#     # return arr.values[0]

# def manPercentage(arr):
#     # return pd.to_numeric(arr.values[1]/arr.sum())*100
#     return arr.values[1].value_counts().count()
#     # arr.values[1]=1
#     # return arr.values[1]

    
# grouped=users.groupby(['occupation'])
# # grouped.gender.value_counts()
# grouped.gender.astype(int).aggregate([womanPercentage,manPercentage])