# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [ ]:
from datetime import datetime
dateRange=pd.date_range(
    start='01/01/2015',end=datetime.today()
)

# dateRange

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [ ]:
# #importing apple stock data from pandas datareader
# from datetime import datetime
# from dotenv import load_dotenv
# # print(load_dotenv)
# load_dotenv()
# import os
# key='API_KEY'
# value=os.getenv('API_KEY')
# start=datetime(2025,1,1)
# end=datetime.now()

# import pandas_datareader.data as web


# # # apple_stock = web.DataReader('AAPL', start=start,end=end,api_key=value)
# data = web.DataReader('AAPL', start, end)
# data.head()

In [ ]:
import pandas as pd
import pandas_datareader.data as web
import datetime as dt 

# import os
# from dotenv import load_dotenv
# load_dotenv()
# key='API_KEY'
# value=os.getenv(key)

start=dt.datetime(2025,1,1)
end=dt.datetime.today()

import yfinance  as yfin
df_apple=yfin.download(
    'AAPL'
)
df_apple.head()

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [ ]:
import numpy as np 
df_apple['stocks']='AAPL'
df_apple.head()

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [ ]:
import yfinance as yfin

tesla=yfin.download(
    tickers='TSLA',
    start=start,
    end=end,

)
tesla['stocks']='TSLA'
#filtering 

ibm=yfin.download(
    'IBM',
    start=start,
    end=end,

)
ibm['stocks']='IBM'
microsoft=yfin.download(
    'MSFT',
    start=start,
    end=end
)
microsoft['stocks']='MSFT'

display(tesla.head())
display(ibm.head())
display(microsoft.head())
display(df_apple.head())

In [ ]:
##Removing Ticket levels from datasets
# print(type(tesla.columns))
tesla.columns=tesla.columns.droplevel(1)
tesla.index=pd.to_datetime(tesla.index)
# tesla.head()

In [ ]:
ibm.columns=ibm.columns.droplevel(1)
ibm.index=pd.to_datetime(ibm.index)

In [ ]:
microsoft.columns=microsoft.columns.droplevel(1)
microsoft.index=pd.to_datetime(microsoft.index)

In [ ]:
df_apple.columns=df_apple.columns.droplevel(1)
df_apple.index=pd.to_datetime(df_apple.index)

In [ ]:
df_apple.index.get_level_values(0)
# df_apple.index.name=''
# df_apple.head()

In [ ]:
##checking current dataFrames
display(tesla.head())
display(ibm.head())
display(microsoft.head())
display(df_apple.head())

In [ ]:
print(type(tesla),type(ibm),type(microsoft),type(df_apple))
print(type(tesla.index),type(ibm.index),type(microsoft.index),type(df_apple.index))

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [ ]:
dfs=[ibm,microsoft,df_apple]
df=pd.concat([ibm,microsoft,df_apple],axis=0)
df.head()
# df.columns
# df.tail()

In [ ]:
# #merging dataframe with merge 
# merged=microsoft.merge(
#     tesla,
#     how='inner',
#     on='Date'
# )
# # merged
# merged1=merged.merge(
#     ibm,
#     how='inner',
#     on='Date'

# )
# # merged1.head()
# df=merged1.merge(
#     df_apple,
#     how='inner',
#     on='Date'
# )
# df.head()
# df.columns.get_level_values(0)

In [ ]:
display(df.index)
display(df.columns)

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [46]:
df.set_index(keys='stocks',append=True,inplace=True)

In [ ]:
# df.set_index(keys='stocks',append=True,inplace=True)

In [ ]:
# df.set_index(keys='stocks_y',append=True,inplace=True)

In [47]:
df.head()

Price                   Close        High         Low        Open   Volume
Date       stocks
2025-01-02 IBM     210.120087  212.556237  207.884567  211.916153  2579500
2025-01-03 IBM     212.709076  213.673991  210.702846  210.702846  3872100
2025-01-06 IBM     212.728180  214.333179  210.893906  213.043448  2846700
2025-01-07 IBM     213.960602  216.587819  212.881050  213.377837  3299300
2025-01-08 IBM     213.215439  214.858645  210.970371  213.912856  2619800

In [45]:
date=df.index.get_level_values(0)
date=pd.DatetimeIndex(date) #ensure that it's a datetime64

### Step 7. Create a dataFrame called vol, with the volume values.

In [ ]:
# vol=pd.DataFrame(
#     {
#         'volume':df.Volume,
        

#     }
# )
# vol.reset_index(inplace=True,drop=True)
# # vol.index=df.index
# vol.head()

In [48]:
##Solution
vol=df['Volume']
vol=pd.DataFrame(vol)
vol

                     Volume
Date       stocks
2025-01-02 IBM      2579500
2025-01-03 IBM      3872100
2025-01-06 IBM      2846700
2025-01-07 IBM      3299300
2025-01-08 IBM      2619800
...                     ...
2026-09-11 AAPL    50716900
2026-09-14 AAPL    39269100
2026-09-15 AAPL    31748200
2026-09-16 AAPL    35981000
2026-09-17 AAPL    36188003

[878 rows x 1 columns]

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [ ]:
# #sorting index (df)
# # pd.to_datetime(df.index.get_level_values(0))
# vol.index=df.index.get_level_values(0)
# # vol.head()

In [ ]:
# vol.sort_index(inplace=True,ascending=True)

In [ ]:
# #creating new dummy values with pd.daterange
# # vol.index.resample(rule='1W').mean()
# vol.resample(rule='1W').mean()

In [ ]:
##Solution
date=vol.index.get_level_values(0)
date=pd.DatetimeIndex(date)

vol['week']=date.isocalendar().week.values

vol['year']=date.year

vol.head()

pd.pivot_table(
    vol,values='Volume',index=['year','week'],
    columns=['stocks'],aggfunc=np.sum
)

stocks            AAPL         IBM         MSFT
year week
2025 1             NaN  16429900.0   73998900.0
     2             NaN  12336100.0   73968400.0
     3             NaN  18989800.0   95676000.0
     4             NaN  15594300.0   87828300.0
     5             NaN  39045300.0  171469100.0
...                ...         ...          ...
2026 34    191766100.0  26432600.0  116216900.0
     35    165636500.0  21177700.0  115404800.0
     36    205019200.0  22079600.0  105819600.0
     37    221845900.0  21915100.0   62321200.0
     38    143186303.0  23330375.0   75195317.0

[90 rows x 3 columns]

### Step 9. Find all the volume traded in the year of 2015

In [ ]:
# filter_=vol.index.year==2025
# vol[filter_]

In [ ]:
vol_2015=vol[vol['year']==2015]

pd.pivot_table(
    vol_2015,values='Volume',index=['year'],
    columns=['stocks'],aggfunc=np.sum
)