# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [113]:
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [121]:
# cars1=pd.read_csv('cars1.csv',sep=',')
# cars2=pd.read_csv('cars2.csv',sep=',')

cars1=pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars2=pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")


print(cars1.head())
print(cars2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [ ]:
##First Approach(BEST APPROACH)

currCols=cars1.iloc[:,9:] #Worked
cars1=cars1.drop(currCols,axis=1)

####################################
##Second Aproach
# currCols=cars1.columns[9:]
# cars1.drop(columns=currCols,inplace=True)
# cars1
#####################################
##Third Approach
# currCols=cars1.columns[9:] #Worked
# cars1.drop(currCols,axis=1,inplace=True)#Worked
# cars1
#####################################
#Solution
# cars1=cars1.loc[:,"mpg":"car"]
# cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [123]:
print("cars1 observation numbers:\t",cars1.shape[0])
print("cars2 observation numbers:\t",cars2.shape[0])

cars1 observation numbers:	 198
cars2 observation numbers:	 200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [117]:
##First Approach
# cars=pd.merge(cars1,cars2,)
##Second Approach
# cars1
# print(cars2.head())
cars=pd.concat([cars1,cars2],axis=0).reset_index(drop=True)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [118]:
import numpy as np
seed=42
rng=np.random.default_rng(seed=seed)
# rng.integers(low=10,high=100,size=8)
# creating new dummy datas
dummyValues=rng.uniform(low=15e3,high=73e3,size=cars.shape[0])
# dummyValues
# creating new DataFrame 
owners=pd.DataFrame(
    {
        "owners":dummyValues
    }
)

### Step 8. Add the column owners to cars

In [119]:
#appending new DataFrame to cars DataFrame
cars=pd.concat([cars,owners],axis=1)
# checking owner features 
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,59889.450816
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,40454.949506
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,64798.679355
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,55447.345685
4,17.0,8,302,140,3449,10.5,70,1,ford torino,20462.286177
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,54793.589176
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,15713.555782
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,41350.441787
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,62873.171649
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,32130.823470