# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [37]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [38]:
# !curl -O 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
import pandas as pd
# drinks=pd.read_csv('drinks.csv',sep=",")
drinks=pd.read_csv('drinks.csv',sep=',',keep_default_na=False)
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

### Step 4. Which continent drinks more beer on average?

In [39]:
# grouped=drinks.groupby(['continent'])['beer_servings'].sum().sort_values(ascending=False)
# # for name,subgroup in grouped:
# #     print(name)
# #     print(subgroup['beer_servings'].sum())
# #     break
    
# grouped

grouped=drinks.groupby(['continent'])
grouped['beer_servings'].sum().sort_values(ascending=False)

continent
EU    8720
NA    3345
AF    3258
SA    2101
AS    1630
OC    1435
Name: beer_servings, dtype: int64

### Step 5. For each continent print the statistics for wine consumption.

In [40]:
# grouped=drinks.groupby(['continent'])['wine_servings'].describe()
# grouped
grouped=drinks.groupby(['continent'])
grouped['wine_servings'].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
NA          23.0   24.521739  28.266378  1.0   5.0   11.0   34.00  100.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [ ]:
grouped=drinks.groupby(['continent'])

# grouped['total_litres_of_pure_alcohol'].mean()
grouped.mean(numeric_only=True)

continent
AF    3.007547
AS    2.170455
EU    8.617778
NA    5.995652
OC    3.381250
SA    6.308333
Name: total_litres_of_pure_alcohol, dtype: float64

### Step 7. Print the median alcohol consumption per continent for every column

In [42]:
grouped=drinks.groupby(['continent'])
grouped['total_litres_of_pure_alcohol'].median()

continent
AF     2.30
AS     1.20
EU    10.00
NA     6.30
OC     1.75
SA     6.85
Name: total_litres_of_pure_alcohol, dtype: float64

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [43]:
# grouped=drinks.groupby([''])
drinks.aggregate({
    'spirit_servings':['mean','min','max']
})

      spirit_servings
mean        80.994819
min          0.000000
max        438.000000