# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [23]:
import pandas as pd

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [24]:
import numpy as np
import pandas as pd

rng=np.random.default_rng(seed=42)

series1=pd.Series(rng.integers(low=1,high=4,size=100),name='series1')
series2=pd.Series(rng.integers(low=1,high=3,size=100),name='series2')
series3=pd.Series(rng.integers(low=10e4,high=3*10e4,size=100),name='series3')

### Step 3. Let's create a DataFrame by joinning the Series by column

In [25]:
df=pd.concat([series1,series2,series3],axis=1)
# df.shape[0]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [37]:
# df.columns=['bedrs','bathrs','price_sql_meter']
# # df.columns
df.rename(
    columns={
        0:'bedrs',
        1:'bathrs',
        2:'price_sqr_meter'
    },
    inplace=True)
df

    bedrs  bathrs  price_sql_meter  bigColumn
0       1       2           173252          1
1       3       1           281716          3
2       2       2           199013          2
3       2       1           239941          2
4       2       2           191483          2
..    ...     ...              ...        ...
95      1       1           204134          1
96      1       1           269955          1
97      3       1           187782          3
98      2       1           156911          2
99      1       2           104322          1

[100 rows x 4 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [39]:
newDf=pd.DataFrame(
    {
        'bigColumn':pd.Series(np.concatenate([series1,series2,series3],axis=0))
    }
)
# newDf.describe()
newDf.shape

(300, 1)

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [38]:
newDf.shape[0]#Yes

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [33]:
index=range(0,299)
df.reindex(index=index)
df['bigColumn']=newDf

   bedrs  bathrs  price_sql_meter  bigColumn
0      1       2           173252          1
1      3       1           281716          3
2      2       2           199013          2
3      2       1           239941          2
4      2       2           191483          2