# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [ ]:
baby_names=pd.read_csv('US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [ ]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [ ]:
baby_names.drop(['Unnamed: 0','Id'],axis=1,inplace=True)

### Step 6. What year has the highest number of baby names in the dataset?

In [ ]:
# baby_names['Name'].value_counts().sort_values(ascending=False)
# grouped=baby_names.groupby('Year')
# series=grouped['Name']
# dict_=dict()

# con=0
# nameCon=''
# for name,val in dict_.items():
#     con=max(val,con)
#     if con==val:
#         nameCon=name

# print(nameCon)
# print(con)

# dict_.
# for name,subgroup in res:

#     dict_[name]=subgroup.sum()

# sorting=sorted(dict_.values())
# sorting[0]

baby_names.groupby('Year').sum().idxmax()

0

### Step 7. Is there more male or female names in the dataset?

In [ ]:
# from collections import Counter
baby_names.Gender.value_counts().sort_values(ascending=False)

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [ ]:
# names=baby_names.groupby(['Name'])['Name']
# # for name,subgroup in grouped:
# #     print(subgroup)
# #     break

#You dont want to sum the Year column,so you delete it
del baby_names['Year']

#group the data
names=baby_names.groupby('Name').sum()

#print the first 5 occurences
names.head()

#print the size of the dataset
print(names.shape)

#sort it from the biggest value to the smallest one
names.sort_values('Count',ascending=False).head()

### Step 9. How many different names exist in the dataset?

In [ ]:
# names.unique().count()
#as we have already grouped by the same,all the names are  unique already.
len(names)

np.int64(17632)

### Step 10. What is the name with most occurrences?

In [ ]:
# names.value_counts().idxmax()
names.Count.idxmax()

'Riley'

### Step 11. How many different names have the least occurrences?

In [ ]:
# names.value_counts().argmin()
len(names[names.Count==names.Count.min()])

np.int64(2)

### Step 12. What is the median name occurrence?

In [ ]:
# maxIndex=names.value_counts().sort_values(ascending=False).reset_index().idxmax()['Name']
# minIndex=names.value_counts().sort_values(ascending=False).reset_index().idxmin()['Name']


# medianIndex=int(int(maxIndex+minIndex)/2)
# names.value_counts().sort_values(ascending=False).reset_index().iloc[medianIndex]
names[names.Count==names.Count.median()]

Name     Kymari
count         3
Name: 11237, dtype: object

### Step 13. What is the standard deviation of names?

In [ ]:
# from statistics import stdev
import numpy as np

np.std(names.value_counts())

np.float64(122.02650299050643)

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
# names.aggregate(
#     {
#         'mean':names.value_counts().mean(),
#         'min':names.value_counts().min(),
#         'max':names.value_counts().max(),
#         'std':names.value_counts().std(),
#         'quartiles':names.value_counts().quantile()
#     }
# )
# names.value_counts().to_frame().agg(
#     {
#         'count':['mean','min','max','std',]
#     }
    
# )
names.describe()

            count
mean    57.644907
min      1.000000
max   1112.000000
std    122.029964