# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [196]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [197]:
#importing required libraries
import os
import time
import shutil

import pandas as pd

file='chipotle.csv'
srcPath='/home/dreams/Projects/webScraping/MachineLearningProject/pandasPractices/pandas_exercises/01_Getting_&_Knowing_Your_Data/Chipotle'
#copying current csv file
if not os.path.exists(os.path.join(os.getcwd(),file)):
    #copying current chipotle csv
    # shutil.copy(srcPath,os.getcwd())
    shutil.copy(os.path.join(srcPath,file),os.getcwd())
    time.sleep(1)
    print('copied to  current path')
else:
    #reading current dataFrame
    chipo=pd.read_csv(file)
# chipo.head(10)
chipo['choice_description'].values[4]

'[Tomatillo-Red Chili Salsa (Hot), [Black Beans, Rice, Cheese, Sour Cream]]'

### Step 4. How many products cost more than $10.00?

In [ ]:
import numpy as np

chipo['prices_float']=chipo['item_price'].astype(str).str.replace("$","",regex=False)
chipo['prices_float']=chipo['prices_float'].astype(np.float64)

mask=(chipo['prices_float']>10)
print(len(chipo[mask]['item_name'].unique()))

31

In [201]:
#creating new dataFrame
df=pd.DataFrame({
        'item_name':chipo['item_name'],
        'choice_description':chipo['choice_description'],
        'item_price':chipo['item_price']
    }
)
df.head()

,item_name,choice_description,item_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

### Step 6. Sort by the name of the item

In [203]:
df.sort_values(by=['item_name'])

,item_name,choice_description,item_price
3389,6 Pack Soft Drink,[Diet Coke],12.98
341,6 Pack Soft Drink,[Diet Coke],6.49
1849,6 Pack Soft Drink,[Coke],6.49
1860,6 Pack Soft Drink,[Diet Coke],6.49
2713,6 Pack Soft Drink,[Coke],6.49
...,...,...,...
2384,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [225]:
chipo.sort_values(by=['item_price'],ascending=False)['quantity'].values[0]

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [226]:
mask=chipo['item_name']=='Veggie Salad Bowl'
chipo['quantity'][mask].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [229]:
#defining filter
mask=(chipo['item_name']=='Canned Soda')&(chipo['quantity']>1)
# chipo=chipo.reset_index(drop=True)
# chipo
# chipo[mask]['quantity'].value_counts()
chipo[mask].shape[0]

20